ktor:
  application:
    modules:
      - com.bs.basicktorserver.ApplicationKt.module
  deployment:
    port: 8080

database:
  driver: "${DB_DRIVER:-org.h2.Driver}"
  url: "${DB_URL:-jdbc:h2:./db/data;DB_CLOSE_DELAY=-1;}"
  user: "${DB_USER:-root}"
  password: "${DB_PASSWORD:-}"
